# file: .travis.yml
dist: focal

language: minimal

addons:
  apt:
    sources:
      - ppa:projectatomic/ppa
    packages:
      - software-properties-common
      - podman
      - buildah

before_install:
  - sudo mkdir -p /etc/containers
  - sudo sh -c 'echo -e "[registries.search]\nregistries = [\"docker.io\"]" > /etc/containers/registries.conf'

script:
  - make all
  - make push
