# file: .travis.yml
dist: bionic

language: minimal

before_install:
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common podman buildah libsecret-tools
  - sudo mkdir -p /etc/containers
  - sudo sh -c 'echo "[registries.search]\nregistries = [\"docker.io\"]" > /etc/containers/registries.conf'
  - cat /etc/containers/registries.conf
  - podman info

env:
  global:
    PATH="$PATH:/usr/lib/cri-o-runc/sbin/"
  jobs:
    - molecule_distribution=alpine
    - molecule_distribution=amazonlinux
    - molecule_distribution=archlinux
    - molecule_distribution=centos
    - molecule_distribution=debian
    - molecule_distribution=fedora
    - molecule_distribution=opensuse
    - molecule_distribution=oraclelinux
    - molecule_distribution=ubuntu

script:
  - make $molecule_distribution

deploy:
  provider: script
  script: make push
  on:
    branch: master
