# file: .travis.yml
dist: bionic

language: minimal

before_install:
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common podman buildah libsecret-tools
  - sudo mkdir -p /etc/containers
  - sudo sh -c 'echo "[registries.search]\nregistries = [\"docker.io\"]" > /etc/containers/registries.conf'
  - cat /etc/containers/registries.conf

env:
  - build_distribution=alpine
  - build_distribution=amazonlinux
  - build_distribution=archlinux
  - build_distribution=centos
  - build_distribution=debian
  - build_distribution=fedora
  - build_distribution=opensuse
  - build_distribution=oraclelinux
  - build_distribution=ubuntu

script:
  - make $build_distribution

jobs:
  include:
    - stage: push
      script: make push
      env: build_distribution=""
